/*
 * OpenAPI Go Reference Service
 *
 * This is a sample Go Reference
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"context"
	"errors"
	"net/http"

	. "github.com/alighm/sample-service/api/gen"
)

// UserAPIService is a service that implements the logic for the UserAPIServicer
// This service should implement the business logic for every endpoint for the UserAPI API.
// Include any external packages or services that will be required by this service.
type UserAPIService struct {
}

// NewUserAPIService creates a default api service
func NewUserAPIService() UserAPIServicer {
	return &UserAPIService{}
}

// AddUser - Add a new user
func (s *UserAPIService) AddUser(ctx context.Context, xRequestID string, user User) (ImplResponse, error) {
	// TODO - update AddUser with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	// return Response(201, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddUser method not implemented")
}

// DeleteUser - Deletes a user
func (s *UserAPIService) DeleteUser(ctx context.Context, xRequestID string, userId string) (ImplResponse, error) {
	// TODO - update DeleteUser with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteUser method not implemented")
}

// GetUser - Find user by ID
func (s *UserAPIService) GetUser(ctx context.Context, xRequestID string, userId string) (ImplResponse, error) {
	// TODO - update GetUser with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, UserView{}) or use other options such as http.Ok ...
	return Response(200, UserView{
		Id:        "52864284-5807-42BD-93B8-79D21BE02D87",
		FirstName: "John",
		LastName:  "Doe",
		Email:     "john.doe@example.com",
	}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	//return Response(http.StatusNotImplemented, nil), errors.New("GetUser method not implemented")
}

// GetUsers - Get all users
func (s *UserAPIService) GetUsers(ctx context.Context, xRequestID string) (ImplResponse, error) {
	// TODO - update GetUsers with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, UserView{}) or use other options such as http.Ok ...
	return Response(200, []UserView{{
		Id:        "52864284-5807-42BD-93B8-79D21BE02D87",
		FirstName: "John",
		LastName:  "Doe",
		Email:     "john.doe@example.com",
	}}), nil

	//return Response(http.StatusNotImplemented, nil), errors.New("GetUsers method not implemented")
}

// UpdateUser - Updates a user
func (s *UserAPIService) UpdateUser(ctx context.Context, xRequestID string, userId string, user User) (ImplResponse, error) {
	// TODO - update UpdateUser with the required logic for this service method.
	// Add api_user_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateUser method not implemented")
}
